### ISSUE TITLE
Object conversion error in notebook

### ISSUE THREAD

**Issue by sla23** [KiranUofG/UNSflow#15]
The following object conversion error occurs in notebook UNSflow/examples/LDVM_example1.ipynb, e.g. in cells [12] and [15]:

MethodError: Cannot `convert` an object of type Float64 to an object of type Array{Float64,1}
This may have arisen from a call to the constructor Array{Float64,1}(...),
since type constructors fall back to convert methods.

 in UNSflow.TwoDSurf(::String, ::Float64, ::UNSflow.KinemDef, ::Float64, ::Float64, ::Float64, ::Int64, ::Int64) at INCOGNITO\UNSflow\src\types.jl:657
 in UNSflow.TwoDSurf(::String, ::Float64, ::UNSflow.KinemDef, ::Float64) at INCOGNITO\UNSflow\src\types.jl:572

**Comment by KiranUofG** [comment]
Please pull the latest version of the repo. I've fixed the error now. 

There was an error in the example. The type TwoDSurf has a field called lespcrit which was wrongly provided as a float - it must be provided as an array. If the value is 0.21, it must be provided as [0.21].
